---
apiVersion: v1
kind: Service
metadata:
  name: sleeper
  labels:
    app: sleeper
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: sleeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper
  labels:
    app: sleeper
spec:
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      containers:
        - name: sleeper
          image: n3a1/sleeper:1.0.0
